spring:
  application:
    name: gateway

cloud:
  gateway:
    routes:
      - id: frontend
        uri: http://frontend:3000
        predicates:
          - Path=/
        filters:
          - Logging
      - id: servicio-a
        uri: http://service-a:8081
        predicates:
          - Path=/api
        filters:
          - Logging
      - id: servicio-b
        uri: http://service-b:8082
        predicates:
          - Path=/bpi
        filters:
          - Logging
    server:
      webflux:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        globalcors:
          cors-configurations:
            "[/**]":
              allowedOrigins: ${ALLOWED_ORIGINS:*}
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
