server:
  port: 8082

spring:
  application:
    name: search-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/streamingonlinedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  elasticsearch:
    rest:
      uris: ${ELASTICSEARCH_URI}
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
